name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
api-version: 1.13
api: 1.13
softdepend:
  - "PlaceholderAPI"
  - "SwiftBoard"
url: ${url}
authors:
  - "joshy23"
commands:
  squidgame:
    aliases: ["sg", "sq", "squid"]
    description: "This is an example plugin."